# Generated by Django 4.1.2 on 2022-11-09 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_alter_card_description_alter_card_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.CharField(max_length=500, validators=[django.core.validators.RegexValidator('^[a-zA-Z,]*$', 'Only alphabets characters are allowed.'), django.core.validators.MinLengthValidator(25, 'the field must contain at least 25 characters')]),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[a-zA-Z,]*$', 'Only alphabets characters are allowed.')]),
        ),
    ]
